[theme]
primaryColor = "#D71920"              # vermelho da marca (mant√©m)
backgroundColor = "#FFFFFF"           # fundo branco
secondaryBackgroundColor = "#F2F2F2"  # cards / sidebar
textColor = "#000000"                 # texto preto
font = "sans serif"
